import { wrapFunctional } from './utils'

export { default as Button } from '../../components/Button.vue'
export { default as GraySeperator } from '../../components/GraySeperator.vue'
export { default as JobList } from '../../components/JobList.vue'
export { default as Link } from '../../components/Link.vue'
export { default as NuxtLogo } from '../../components/NuxtLogo.vue'
export { default as OkBtn } from '../../components/OkBtn.vue'
export { default as SideMenu } from '../../components/SideMenu.vue'
export { default as Table } from '../../components/Table.vue'
export { default as Tutorial } from '../../components/Tutorial.vue'
